modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="dogtags"
version="1.14.4-1.0.0.1"
displayName="DogTags"
authors="Choco"
description='''
Give collars to your pets (wolves and cats) and receive a final goodbye from your fallen allies.
'''

[[dependencies.dogtags]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dogtags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
